
const KEY='wk_transport_site_v3';
const INIT={packaging:window.INIT_PACKAGING||[],planning:[],history:[],config:{capacity:52,minOcc:85,maxOcc:100,windows:2,windowMode:'fixed',baselineVehicles:3,costPerVehicle:1797.34,routeKm:68.8,ttw:0.78471,wtt:0.18538,periodWeeks:18,weekLabel:'S34–S51'}};
let db=loadDB(), rawWorkbook=null, rawSheetRows=[], editingPack=null;
function clone(x){return JSON.parse(JSON.stringify(x))} function loadDB(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x&&x.config&&x.packaging)return x}catch(e){}return clone(INIT)} function persist(){localStorage.setItem(KEY,JSON.stringify(db))}
const $=id=>document.getElementById(id); const n=(v,d=0)=>Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}); const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const pct=v=>n(v*100,1)+'%';
function nav(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(b.dataset.page).classList.add('active');const titles={dashboard:['Dashboard executivo','Visão consolidada da necessidade de transporte WK'],planning:['Planejamento semanal','Importe o arquivo de receipts e calcule pallets/veículos'],packaging:['Base de embalagens','Cadastro mestre de lote e capacidade por material'],impacts:['Impactos da ação','Saving, viagens evitadas e redução estimada de CO₂e'],loading3d:['Carregamento 3D','Visualização da ocupação prevista por janela e por carreta'],config:['Configurações','Parâmetros editáveis do modelo']};$('pageTitle').textContent=titles[b.dataset.page][0];$('pageSub').textContent=titles[b.dataset.page][1];renderAll()})}
function packageMap(){let m=new Map();db.packaging.forEach(r=>m.set(String(r.material).trim().toUpperCase(),r));return m}
function qtyOf(r){let mode=$('qtyMode')?.value||'sum',p=+r.planned||0,f=+r.firmed||0;return mode==='planned'?p:mode==='firmed'?f:mode==='max'?Math.max(p,f):p+f}
function processed(){let pm=packageMap();return db.planning.map(r=>{let p=pm.get(String(r.material||'').trim().toUpperCase()),q=qtyOf(r),ipp=p?+p.itemsPerPallet||0:0,pals=ipp?Math.ceil(q/ipp):0;return {...r,quantity:q,pack:p,itemsPerPallet:ipp,pallets:pals,status:p?'OK':'SEM EMBALAGEM'}})}
function totals(){let pr=processed(),pallets=pr.reduce((a,r)=>a+r.pallets,0),pieces=pr.reduce((a,r)=>a+r.quantity,0),missing=pr.filter(r=>r.status!=='OK').length;let opt=optimize(pallets);return{pieces,pallets,missing,...opt}}
function splitBalanced(total,k){if(k<=0)return[];let base=Math.floor(total/k),rem=total%k;return Array.from({length:k},(_,i)=>base+(i<rem?1:0))}
function planForWindows(total,w){let c=db.config.capacity,arr=splitBalanced(total,w);let windows=arr.map((p,i)=>{let vehicles=p?Math.ceil(p/c):0,occ=vehicles?p/(vehicles*c):0,status=occ>db.config.maxOcc/100?'ACIMA DE 100%':occ<db.config.minOcc/100?'ABAIXO DE 85%':'OK';return{window:i+1,pallets:p,vehicles,occ,status}});let vehicles=windows.reduce((a,x)=>a+x.vehicles,0),cap=vehicles*c,occ=vehicles?total/cap:0;return{windows,vehicles,occ}}
function optimize(total){let maxW=Math.max(1,+db.config.windows||1);if(db.config.windowMode==='fixed')return planForWindows(total,maxW);let candidates=[];for(let w=1;w<=maxW;w++){let p=planForWindows(total,w),under=p.windows.filter(x=>x.pallets&&x.occ<db.config.minOcc/100).length;candidates.push({...p,w,under})}candidates.sort((a,b)=>a.vehicles-b.vehicles||a.under-b.under||b.occ-a.occ||b.w-a.w);return candidates[0]}
function impact(){let t=totals(),base=+db.config.baselineVehicles||0,current=t.vehicles,avoided=Math.max(0,base-current),saving=avoided*db.config.costPerVehicle,km=avoided*db.config.routeKm,ttw=km*db.config.ttw,wtw=km*(db.config.ttw+db.config.wtt),weeks=+db.config.periodWeeks||1;return{...t,base,current,avoided,saving,km,ttw,wtw,weeks,totalSaving:saving*weeks,totalKm:km*weeks,totalTTW:ttw*weeks,totalWTW:wtw*weeks,reduction:base?avoided/base:0}}
function statusBadge(s){let cl=s==='OK'?'ok':s.includes('ABAIXO')||s.includes('SEM')?'warn':'bad';return `<span class="badge ${cl}">${s}</span>`}
function renderDashboard(){let t=totals(),im=impact(),items=[['Peças planejadas',n(t.pieces),'Quantidade usada no cálculo'],['Pallets necessários',n(t.pallets),'Arredondamento por material'],['Carretas/semana',n(t.vehicles),`${db.config.windows} janela(s) configurada(s)`],['Ocupação média',pct(t.occ),'Meta: '+db.config.minOcc+'%–'+db.config.maxOcc+'%'],['Saving semanal',money(im.saving),`${n(im.avoided)} viagem(ns) evitada(s)`],['CO₂e evitado/sem.',n(im.ttw/1000,2)+' t','Estimativa TTW']];$('kpiGrid').innerHTML=items.map(x=>`<div class="card kpi"><div class="lab">${x[0]}</div><div class="val">${x[1]}</div><div class="foot">${x[2]}</div></div>`).join('');$('windowCards').innerHTML=t.windows.length?t.windows.map(w=>`<div class="window"><div class="head"><span>Janela ${w.window}</span><span>${w.vehicles} carreta(s)</span></div><div class="smalltxt">${w.pallets} pallets • ocupação ${pct(w.occ)} • ${statusBadge(w.status)}</div><div class="progress" style="margin-top:8px"><div style="width:${Math.min(100,w.occ*100)}%"></div></div></div>`).join(''):'<div class="smalltxt">Importe um planejamento para iniciar.</div>';let cls=t.missing?'warnbox':t.pallets?'okbox':'';$('planSummary').className='notice '+cls;$('planSummary').innerHTML=t.pallets?`O planejamento demanda <b>${n(t.pallets)} pallets</b> e <b>${n(t.vehicles)} carreta(s)</b>. Ocupação média de <b>${pct(t.occ)}</b>. ${t.missing?`Existem <b>${t.missing} material(is)</b> sem cadastro de embalagem; esses itens não entram corretamente no total de pallets até serem cadastrados.`:'Todos os materiais possuem embalagem cadastrada.'}`:'Importe o Planejamento Semanal para calcular a necessidade de transporte.';let crit=processed().filter(r=>r.status!=='OK').slice(0,8);$('criticalSummary').innerHTML=crit.length?crit.map(r=>`<div class="window"><b>${r.material}</b><div class="smalltxt">Sem lote cadastrado • quantidade ${n(r.quantity)}</div></div>`).join(''):'<div class="notice okbox">Nenhum material crítico no planejamento atual.</div>';drawOcc(t.windows)}
function renderPlan(){let rows=processed();$('planRows').innerHTML=rows.map(r=>`<tr><td><b>${r.material}</b></td><td>${r.pack?.description||r.description||''}</td><td class="num">${n(r.planned)}</td><td class="num">${n(r.firmed)}</td><td class="num">${n(r.quantity)}</td><td class="num">${r.itemsPerPallet?n(r.itemsPerPallet):'—'}</td><td class="num"><b>${r.status==='OK'?n(r.pallets):'—'}</b></td><td>${statusBadge(r.status)}</td></tr>`).join('');$('planMeta').textContent=rows.length?`${rows.length} materiais • ${n(rows.reduce((a,r)=>a+r.quantity,0))} peças • ${n(rows.reduce((a,r)=>a+r.pallets,0))} pallets calculados`:'Nenhum planejamento processado.'}
function renderPackaging(){let q=($('packSearch')?.value||'').toLowerCase(),arr=db.packaging.filter(r=>!q||[r.material,r.description,r.supplier].some(x=>String(x||'').toLowerCase().includes(q)));$('packCount').textContent=db.packaging.length;$('packRows').innerHTML=arr.map(r=>{let idx=db.packaging.indexOf(r);return `<tr><td>${r.supplier||''}</td><td><b>${r.material}</b></td><td>${r.description||''}</td><td class="num">${n(r.itemsPerBox)}</td><td class="num">${n(r.boxesPerPallet)}</td><td class="num"><b>${n(r.itemsPerPallet)}</b></td><td><button class="btn small" onclick="openPackModal(${idx})">Editar</button> <button class="btn small danger" onclick="deletePack(${idx})">Excluir</button></td></tr>`}).join('')}
function renderImpacts(){let x=impact(),items=[['Viagens evitadas/sem.',n(x.avoided),`${n(x.base)} → ${n(x.current)}`],['Redução',pct(x.reduction),'Quantidade de veículos'],['Saving semanal',money(x.saving),'Custo direto'],['Saving período',money(x.totalSaving),db.config.weekLabel],['Km evitados',n(x.totalKm)+' km','No período'],['CO₂e evitado',n(x.totalTTW/1000,2)+' t','TTW no período']];$('impactKpis').innerHTML=items.map(a=>`<div class="card kpi"><div class="lab">${a[0]}</div><div class="val">${a[1]}</div><div class="foot">${a[2]}</div></div>`).join('');$('impactText').innerHTML=`No período <b>${db.config.weekLabel}</b> (${n(x.weeks)} semanas), o cenário atual representa <b>${n(x.avoided*x.weeks)} viagens evitadas</b>, <b>${money(x.totalSaving)}</b> de economia, <b>${n(x.totalKm)} km</b> não rodados e aproximadamente <b>${n(x.totalTTW/1000,2)} t CO₂e TTW</b> evitadas. Considerando WTW: <b>${n(x.totalWTW/1000,2)} t CO₂e</b>.`;$('historyRows').innerHTML=db.history.slice().reverse().map(h=>`<tr><td>${h.date}</td><td>${h.week}</td><td class="num">${n(h.pallets)}</td><td class="num">${n(h.vehicles)}</td><td class="num">${pct(h.occ)}</td><td class="num">${money(h.saving)}</td><td class="num">${n(h.ttw/1000,2)} t</td></tr>`).join('');drawImpact(x)}
function renderConfig(){let c=db.config,fields=[['capacity','Capacidade carreta (pallets)','number'],['minOcc','Ocupação mínima (%)','number'],['maxOcc','Ocupação máxima (%)','number'],['windows','Quantidade de janelas','number'],['baselineVehicles','Veículos antes / semana','number'],['costPerVehicle','Custo por carreta (R$)','number'],['routeKm','Distância da rota (km)','number'],['ttw','Fator CO₂ TTW (kg/km)','number'],['wtt','Fator CO₂ WTT (kg/km)','number'],['periodWeeks','Semanas no período','number'],['weekLabel','Identificação do período','text']];$('configFields').innerHTML=fields.map(f=>`<div class="field"><label>${f[1]}</label><input id="cfg_${f[0]}" type="${f[2]}" step="any" value="${c[f[0]]}"></div>`).join('')+`<div class="field"><label>Modo de janelas</label><select id="cfg_windowMode"><option value="fixed" ${c.windowMode==='fixed'?'selected':''}>Quantidade fixa</option><option value="optimize" ${c.windowMode==='optimize'?'selected':''}>Otimizar até o máximo</option></select></div>`}
function saveConfig(){['capacity','minOcc','maxOcc','windows','baselineVehicles','costPerVehicle','routeKm','ttw','wtt','periodWeeks'].forEach(k=>db.config[k]=+$('cfg_'+k).value);db.config.weekLabel=$('cfg_weekLabel').value;db.config.windowMode=$('cfg_windowMode').value;persist();renderAll();alert('Parâmetros salvos.')}
function renderAll(){renderDashboard();renderPlan();renderPackaging();renderImpacts();renderConfig();renderLoading3D()}
function openPackModal(idx=null){editingPack=idx;let r=idx===null?{supplierCode:'',supplier:'',material:'',description:'',itemsPerBox:0,boxesPerPallet:0,itemsPerPallet:0,unit:'PC'}:db.packaging[idx];$('packModalTitle').textContent=idx===null?'Novo material':'Editar material';let fields=[['supplierCode','Código fornecedor'],['supplier','Fornecedor'],['material','Material'],['description','Descrição'],['itemsPerBox','Itens por caixa','number'],['boxesPerPallet','Caixas por pallet','number'],['itemsPerPallet','Itens por pallet / lote','number'],['unit','Unidade']];$('packForm').innerHTML=fields.map(f=>`<div class="field"><label>${f[1]}</label><input id="pf_${f[0]}" type="${f[2]||'text'}" step="any" value="${String(r[f[0]]??'').replace(/"/g,'&quot;')}"></div>`).join('');$('packModal').classList.add('show')}
function closePackModal(){$('packModal').classList.remove('show')} function savePackRecord(){let r={};['supplierCode','supplier','material','description','unit'].forEach(k=>r[k]=$('pf_'+k).value.trim());['itemsPerBox','boxesPerPallet','itemsPerPallet'].forEach(k=>r[k]=+$('pf_'+k).value||0);if(!r.itemsPerPallet&&r.itemsPerBox&&r.boxesPerPallet)r.itemsPerPallet=r.itemsPerBox*r.boxesPerPallet;if(!r.material){alert('Informe o material.');return}if(editingPack===null){let dup=db.packaging.findIndex(x=>String(x.material).toUpperCase()===r.material.toUpperCase());if(dup>=0&&!confirm('Material já existe. Substituir?'))return;if(dup>=0)db.packaging[dup]=r;else db.packaging.push(r)}else db.packaging[editingPack]=r;persist();closePackModal();renderAll()}
function deletePack(i){if(confirm('Excluir este material da base?')){db.packaging.splice(i,1);persist();renderAll()}}
function loadDemoPlan(){db.planning=clone(window.DEMO_PLAN||[]);$('qtyMode').value='sum';persist();renderAll();showPage('planning')}
function showPage(p){document.querySelector(`.nav button[data-page="${p}"]`).click()}
function headerNorm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function guess(headers,patterns){let norm=headers.map(headerNorm);for(let p of patterns){let i=norm.findIndex(x=>x===p||x.includes(p));if(i>=0)return headers[i]}return ''}
function readPlanningFile(e){let file=e.target.files[0];if(!file)return;if(typeof XLSX==='undefined'){alert('A biblioteca de Excel não carregou. Conecte à internet ou use CSV.');return}let fr=new FileReader();fr.onload=ev=>{try{rawWorkbook=XLSX.read(ev.target.result,{type:'array'});$('sheetSelect').innerHTML=rawWorkbook.SheetNames.map(s=>`<option>${s}</option>`).join('');changePlanSheet();$('mapModal').classList.add('show')}catch(err){alert('Não foi possível ler o arquivo: '+err.message)}};fr.readAsArrayBuffer(file)}
function changePlanSheet(){let s=$('sheetSelect').value||rawWorkbook.SheetNames[0],ws=rawWorkbook.Sheets[s];rawSheetRows=XLSX.utils.sheet_to_json(ws,{defval:''});let headers=rawSheetRows.length?Object.keys(rawSheetRows[0]):[];let defs=[['material','Material',guess(headers,['material','part number','partnumber','codigo material'])],['description','Descrição',guess(headers,['descricao','description'])],['planned','Planned Receipts',guess(headers,['planned receipts','planned receipt','planned'])],['firmed','Firmed Receipts',guess(headers,['firmed receipts','firmed receipt','firmed'])]];$('mappingFields').innerHTML=defs.map(d=>`<div class="field"><label>${d[1]}</label><select id="map_${d[0]}"><option value="">— não usar —</option>${headers.map(h=>`<option ${h===d[2]?'selected':''}>${h}</option>`).join('')}</select></div>`).join('');renderPreview(headers)}
function renderPreview(headers){let hs=headers.slice(0,8),rows=rawSheetRows.slice(0,6);$('previewTable').innerHTML=`<thead><tr>${hs.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${hs.map(h=>`<td>${r[h]}</td>`).join('')}</tr>`).join('')}</tbody>`}
function closeMapModal(){$('mapModal').classList.remove('show')} function toNum(v){if(typeof v==='number')return v;let s=String(v||'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'');return +s||0}
function applyMapping(){let m={};['material','description','planned','firmed'].forEach(k=>m[k]=$('map_'+k).value);if(!m.material){alert('Mapeie a coluna Material.');return}if(!m.planned&&!m.firmed){alert('Mapeie Planned Receipts e/ou Firmed Receipts.');return}let agg=new Map();rawSheetRows.forEach(r=>{let mat=String(r[m.material]||'').trim();if(!mat)return;let key=mat.toUpperCase(),cur=agg.get(key)||{material:mat,description:m.description?String(r[m.description]||''):'',planned:0,firmed:0};cur.planned+=m.planned?toNum(r[m.planned]):0;cur.firmed+=m.firmed?toNum(r[m.firmed]):0;agg.set(key,cur)});db.planning=[...agg.values()];persist();closeMapModal();renderAll();showPage('planning')}
function reprocessPlan(){renderAll()} function exportProcessed(){if(typeof XLSX==='undefined'){alert('Biblioteca Excel indisponível.');return}let data=processed().map(r=>({'Material':r.material,'Descrição':r.pack?.description||r.description||'','Planned Receipts':r.planned,'Firmed Receipts':r.firmed,'Quantidade cálculo':r.quantity,'Itens por pallet':r.itemsPerPallet,'Pallets':r.status==='OK'?r.pallets:'','Status':r.status}));let ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Planejamento Processado');XLSX.writeFile(wb,'WK_Planejamento_Processado.xlsx')}
function importPackaging(e){let f=e.target.files[0];if(!f)return;if(typeof XLSX==='undefined'){alert('Biblioteca Excel indisponível.');return}let fr=new FileReader();fr.onload=ev=>{try{let wb=XLSX.read(ev.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''}),headers=rows.length?Object.keys(rows[0]):[],gm=guess(headers,['part number','material']),gd=guess(headers,['descricao','description']),gb=guess(headers,['fornecedor','supplier']),gq=guess(headers,['parts pu','items per box','itens por caixa']),gj=guess(headers,['pu hu','boxes per pallet','caixas por pallet']),gr=guess(headers,['lote','items per pallet','itens por pallet']);if(!gm){alert('Não identifiquei a coluna Material/Part number.');return}let map=new Map(db.packaging.map((r,i)=>[String(r.material).toUpperCase(),i]));let added=0,upd=0;rows.forEach(row=>{let mat=String(row[gm]||'').trim();if(!mat)return;let rec={supplierCode:'',supplier:gb?String(row[gb]||''):'',material:mat,description:gd?String(row[gd]||''):'',itemsPerBox:gq?toNum(row[gq]):0,boxesPerPallet:gj?toNum(row[gj]):0,itemsPerPallet:gr?toNum(row[gr]):0,unit:'PC'};if(!rec.itemsPerPallet)rec.itemsPerPallet=rec.itemsPerBox*rec.boxesPerPallet;let k=mat.toUpperCase();if(map.has(k)){db.packaging[map.get(k)]={...db.packaging[map.get(k)],...rec};upd++}else{db.packaging.push(rec);map.set(k,db.packaging.length-1);added++}});persist();renderAll();alert(`Importação concluída: ${added} novos e ${upd} atualizados.`)}catch(err){alert('Erro ao importar base: '+err.message)}};fr.readAsArrayBuffer(f)}
function saveScenario(){let x=impact();db.history.push({date:new Date().toLocaleString('pt-BR'),week:db.config.weekLabel,pallets:x.pallets,vehicles:x.vehicles,occ:x.occ,saving:x.saving,ttw:x.ttw});persist();renderImpacts();alert('Cenário salvo no histórico.')}
function exportBackup(){let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='WK_Transport_Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function resetAll(){if(confirm('Restaurar base inicial e apagar planejamento/histórico local?')){db=clone(INIT);persist();renderAll()}}
function svgEl(nm,a={}){let e=document.createElementNS('http://www.w3.org/2000/svg',nm);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));return e}function st(s,x,y,v,z=11,anc='middle',fill='#6f7c89',wt='400'){let e=svgEl('text',{x,y,'font-size':z,'text-anchor':anc,fill,'font-weight':wt});e.textContent=v;s.appendChild(e)}
function drawOcc(ws){let s=$('occChart');s.innerHTML='';let mx=1.05,base=215,barW=550/Math.max(1,ws.length);[db.config.minOcc/100,db.config.maxOcc/100].forEach(v=>{let y=base-v/mx*165;s.appendChild(svgEl('line',{x1:75,y1:y,x2:650,y2:y,stroke:v>=1?'#b42318':'#9a6700','stroke-dasharray':'5 5'}));st(s,67,y+4,Math.round(v*100)+'%',10,'end')});ws.forEach((w,i)=>{let x=90+i*barW,h=Math.min(mx,w.occ)/mx*165,y=base-h,col=w.occ>=db.config.minOcc/100&&w.occ<=1?'#4f9b53':w.occ<db.config.minOcc/100?'#e0a92f':'#bd4b43';s.appendChild(svgEl('rect',{x,y,width:Math.max(28,barW-18),height:h,rx:6,fill:col}));st(s,x+(barW-18)/2,y-8,pct(w.occ),11,'middle','#15345d','700');st(s,x+(barW-18)/2,238,'J'+w.window,11)})}
function drawImpact(x){let s=$('impactChart');s.innerHTML='';let vals=[x.base,x.current],mx=Math.max(1,...vals)*1.25,xp=[225,480],co=['#1f5f93','#8bb4d3'];vals.forEach((v,i)=>{let h=160*v/mx,y=210-h;s.appendChild(svgEl('rect',{x:xp[i]-60,y,width:120,height:h,rx:8,fill:co[i]}));st(s,xp[i],y-10,n(v),20,'middle','#15345d','800');st(s,xp[i],235,i?'Plano otimizado':'Antes',12)});st(s,350,35,'Carretas por semana',13,'middle','#15345d','700')}

// ===== Carregamento 3D =====
let loadYaw=-32*Math.PI/180, loadPitch=23*Math.PI/180, loadDragging=false, loadLastX=0, loadLastY=0;
function vehicleLoadsForWindow(w){
  if(!w||!w.vehicles)return [];
  let remaining=w.pallets,loads=[];
  for(let i=0;i<w.vehicles;i++){let q=Math.min(db.config.capacity,remaining);loads.push(q);remaining-=q}
  // redistribui para melhor balanceamento visual entre veículos da mesma janela
  if(w.vehicles>1){let base=Math.floor(w.pallets/w.vehicles),rem=w.pallets%w.vehicles;loads=Array.from({length:w.vehicles},(_,i)=>base+(i<rem?1:0))}
  return loads;
}
function renderLoading3D(){
  if(!$('loadWindow'))return;
  let t=totals(), oldW=$('loadWindow').value;
  $('loadWindow').innerHTML=t.windows.length?t.windows.map(w=>`<option value="${w.window}">Janela ${w.window} • ${w.pallets} pallets</option>`).join(''):'<option>Sem planejamento</option>';
  if(oldW&&[...$('loadWindow').options].some(o=>o.value===oldW))$('loadWindow').value=oldW;
  refreshLoadVehicles(false);
  let selW=t.windows.find(w=>String(w.window)===$('loadWindow').value)||t.windows[0], loads=vehicleLoadsForWindow(selW), selected=+$('loadVehicle').value||1, pallets=loads[selected-1]||0, occ=pallets/(+db.config.capacity||52);
  let status=occ>=db.config.minOcc/100&&occ<=db.config.maxOcc/100?'Dentro da faixa':occ<db.config.minOcc/100?'Abaixo de 85%':'Acima de 100%';
  $('loadKpis').innerHTML=[['Janela',selW?'J'+selW.window:'—','Selecionada'],['Carreta',loads.length?selected+' de '+loads.length:'—','Veículo selecionado'],['Pallets',n(pallets),`Capacidade ${n(db.config.capacity)}`],['Ocupação',pct(occ),status],['Posições livres',n(Math.max(0,db.config.capacity-pallets)),'Capacidade residual'],['Camadas',pallets>26?'2':'1','Máximo de 2']].map(x=>`<div class="card kpi"><div class="lab">${x[0]}</div><div class="val">${x[1]}</div><div class="foot">${x[2]}</div></div>`).join('');
  let cls=occ>=db.config.minOcc/100&&occ<=db.config.maxOcc/100?'okbox':occ<db.config.minOcc/100?'warnbox':'badbox';
  $('loadDetail').className='notice '+cls;$('loadDetail').innerHTML=selW?`A <b>Janela ${selW.window}</b> prevê <b>${selW.pallets} pallets</b> em <b>${selW.vehicles} carreta(s)</b>. A carreta selecionada recebe <b>${pallets} pallets</b>, correspondendo a <b>${pct(occ)}</b> de ocupação. ${status==='Dentro da faixa'?'Está dentro da faixa operacional de 85% a 100%.':status==='Abaixo de 85%'?'Está abaixo da ocupação mínima desejada de 85%; o sistema mantém o menor número físico de veículos.':'Ultrapassa a capacidade configurada e deve ser replanejada.'}`:'Importe um planejamento para gerar o carregamento.';
  renderLayerMaps(pallets);
  render3DLoad();
}
function refreshLoadVehicles(doRender=true){
  if(!$('loadWindow')||!$('loadVehicle'))return;
  let t=totals(),w=t.windows.find(x=>String(x.window)===$('loadWindow').value)||t.windows[0],loads=vehicleLoadsForWindow(w),old=$('loadVehicle').value;
  $('loadVehicle').innerHTML=loads.length?loads.map((q,i)=>`<option value="${i+1}">Carreta ${i+1} • ${q} pallets • ${pct(q/db.config.capacity)}</option>`).join(''):'<option value="1">Sem veículo</option>';
  if(old&&[...$('loadVehicle').options].some(o=>o.value===old))$('loadVehicle').value=old;
  if(doRender)renderLoading3D();
}
function renderLayerMaps(pallets){
  if(!$('layerMaps'))return;let perLayer=26,html='';
  for(let l=0;l<2;l++){let used=Math.max(0,Math.min(perLayer,pallets-l*perLayer));html+=`<div class="layer-title">${l===0?'1ª camada (piso)':'2ª camada (superior)'} • ${used}/26 pallets</div><div class="layer-grid">`;
    for(let i=0;i<26;i++)html+=`<div class="slot ${i<used?'used':''}">${i<used?i+1:''}</div>`;
    html+='</div>';
  }$('layerMaps').innerHTML=html;
}
function currentLoadPallets(){let t=totals(),w=t.windows.find(x=>String(x.window)===$('loadWindow')?.value)||t.windows[0],loads=vehicleLoadsForWindow(w),v=+$('loadVehicle')?.value||1;return loads[v-1]||0}
function project3D(x,y,z,cx,cy,scale){
  let cyw=Math.cos(loadYaw),syw=Math.sin(loadYaw),cp=Math.cos(loadPitch),sp=Math.sin(loadPitch);
  let x1=x*cyw-z*syw,z1=x*syw+z*cyw,y1=y*cp-z1*sp,z2=y*sp+z1*cp;
  return [cx+x1*scale,cy-y1*scale,z2];
}
function poly(ctx,pts,fill,stroke='#6f542d'){ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i][0],pts[i][1]);ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=.7;ctx.stroke()}
function box3D(ctx,x,y,z,w,h,d,fill,alpha=1){
  let cx=455,cy=330,sc=26, P=(a,b,c)=>project3D(a,b,c,cx,cy,sc),v=[P(x,y,z),P(x+w,y,z),P(x+w,y+h,z),P(x,y+h,z),P(x,y,z+d),P(x+w,y,z+d),P(x+w,y+h,z+d),P(x,y+h,z+d)];
  ctx.save();ctx.globalAlpha=alpha;let faces=[[0,1,2,3],[1,5,6,2],[4,5,6,7],[0,4,7,3]];let shades=[fill,'#c78e3d','#e5bd7a','#b77a2d'];faces.map(f=>({f,depth:f.reduce((a,i)=>a+v[i][2],0)/4})).sort((a,b)=>a.depth-b.depth).forEach((o,j)=>poly(ctx,o.f.map(i=>v[i]),shades[j%shades.length]));ctx.restore();
}
function line3(ctx,a,b,color='#31506d',lw=1.2){ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.stroke()}
function render3DLoad(){
  let c=$('loadCanvas');if(!c)return;let ctx=c.getContext('2d'),D=devicePixelRatio||1,rect=c.getBoundingClientRect();if(rect.width&&c.width!==Math.round(rect.width*D)){c.width=Math.round(rect.width*D);c.height=Math.round(rect.width*.565*D);ctx.setTransform(D,0,0,D,0,0)}else ctx.setTransform(D,0,0,D,0,0);
  let W=c.width/D,H=c.height/D;ctx.clearRect(0,0,W,H);let grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#fbfdff');grad.addColorStop(1,'#eaf1f6');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
  // coordenadas simplificadas: comprimento 13, largura 2, altura 2 camadas
  let P=(x,y,z)=>project3D(x,y,z,W*.5,H*.63,Math.min(31,W/29));
  // piso da carreta
  let floor=[P(-6.7,0,-1.25),P(6.7,0,-1.25),P(6.7,0,1.25),P(-6.7,0,1.25)];poly(ctx,floor,'#dfe6ec','#5c7184');
  // estrutura translúcida
  let corners=[];[-6.7,6.7].forEach(x=>[0,2.15].forEach(y=>[-1.25,1.25].forEach(z=>corners.push(P(x,y,z)))));
  const segs=[[0,4],[1,5],[2,6],[3,7],[0,1],[2,3],[4,5],[6,7],[0,2],[1,3],[4,6],[5,7]];segs.forEach(([a,b])=>line3(ctx,corners[a],corners[b],'#61798d',1.4));
  let pals=currentLoadPallets(),positions=[];
  for(let layer=0;layer<2;layer++)for(let col=0;col<13;col++)for(let row=0;row<2;row++)positions.push({layer,col,row});
  // desenhar de trás para frente pelo depth
  let boxes=positions.slice(0,Math.min(pals,52)).map(p=>{let x=-6.25+p.col*1.0,z=-1.08+p.row*1.08,y=.08+p.layer*.83,center=P(x+.46,y+.38,z+.48);return {...p,x,y,z,depth:center[2]}}).sort((a,b)=>a.depth-b.depth);
  boxes.forEach(b=>box3D(ctx,b.x,b.y,b.z,.9,.72,.96,'#d9a75b',.98));
  ctx.fillStyle='#17365d';ctx.font='700 16px Arial';ctx.fillText(`${pals} pallets • ${pct(pals/(+db.config.capacity||52))} ocupação`,18,28);ctx.font='12px Arial';ctx.fillStyle='#687887';ctx.fillText('13 posições × 2 na largura × 2 camadas = 52 posições',18,48);
}
function rotateLoad(deg){loadYaw+=deg*Math.PI/180;render3DLoad()}
function resetLoadView(){loadYaw=-32*Math.PI/180;loadPitch=23*Math.PI/180;render3DLoad()}
function setupLoadCanvas(){let c=$('loadCanvas');if(!c||c.dataset.ready)return;c.dataset.ready='1';c.addEventListener('pointerdown',e=>{loadDragging=true;loadLastX=e.clientX;loadLastY=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!loadDragging)return;loadYaw+=(e.clientX-loadLastX)*.008;loadPitch=Math.max(-.25,Math.min(1.15,loadPitch+(e.clientY-loadLastY)*.005));loadLastX=e.clientX;loadLastY=e.clientY;render3DLoad()});c.addEventListener('pointerup',()=>loadDragging=false);c.addEventListener('pointercancel',()=>loadDragging=false)}

nav();renderAll();setupLoadCanvas();window.addEventListener('resize',render3DLoad);
