const KEY='wk-transport-planner-v3';
const DEFAULT={config:{capacity:52,minOcc:85,maxOcc:100,cost:1797.34,distance:68.8,ttw:0.78471,wtt:0.18538,windows:2,periodWeeks:18,beforePerWeek:3,weekLabel:'S34–S51'},packaging:window.INIT_PACKAGING||[],plan:window.DEMO_PLAN||[],history:[]};
let db=loadDB();let currentBook=null,currentRows=[],mapping={};let editingPack=-1;let angle=-36,drag=false,lastX=0,lastY=0;
function clone(x){return JSON.parse(JSON.stringify(x))}function loadDB(){try{let x=JSON.parse(localStorage.getItem(KEY));return x||clone(DEFAULT)}catch(e){return clone(DEFAULT)}}function persist(){localStorage.setItem(KEY,JSON.stringify(db))}
function fmt(v,d=0){return Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d})}function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function pct(v){return fmt(v*100,1)+'%'}function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
const titles={dashboard:['Dashboard executivo','Visão consolidada da necessidade de transporte WK'],loading3d:['Carregamento 3D','Visualização prevista da ocupação por janela e veículo'],planning:['Planejamento semanal','Importe Planned Receipts e Firmed Receipts'],packaging:['Base de Embalagens','Cadastro editável de materiais e lotes'],impacts:['Impactos da otimização','Saving, viagens e CO₂ evitado'],config:['Configurações','Parâmetros operacionais do cálculo']};
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.page).classList.add('active');pageTitle.textContent=titles[b.dataset.page][0];pageSub.textContent=titles[b.dataset.page][1];render()});
function packIndex(){const m={};db.packaging.forEach(p=>{if(p.material)m[String(p.material).trim().toUpperCase()]=p});return m}
function usedQty(r){let p=+r.planned||0,f=+r.firmed||0,m=document.getElementById('qtyMode')?.value||'sum';return m==='planned'?p:m==='firmed'?f:m==='max'?Math.max(p,f):p+f}
function lineCalc(r){let pk=packIndex()[String(r.material||'').trim().toUpperCase()],qty=usedQty(r),ipp=pk?+pk.itemsPerPallet||0:0;return{qty,pk,ipp,pallets:ipp>0?Math.ceil(qty/ipp):0,status:!pk?'SEM EMBALAGEM':ipp<=0?'LOTE INVÁLIDO':'OK'}}
function optimizeVehicles(pallets){const c=db.config,cap=c.capacity,n=Math.ceil(Math.max(0,pallets)/cap);if(!pallets)return[];let out=[],base=Math.floor(pallets/n),extra=pallets%n;for(let i=0;i<n;i++){let load=base+(i<extra?1:0);out.push({pallets:load,occ:load/cap})}return out}
function totals(){let lines=db.plan.map((r,i)=>({...lineCalc(r),row:r,index:i})),pieces=lines.reduce((a,x)=>a+x.qty,0),pallets=lines.reduce((a,x)=>a+x.pallets,0),w=Math.max(1,db.config.windows),windowPallets=Array(w).fill(0);for(let i=0;i<pallets;i++)windowPallets[i%w]++;let vehicles=[];windowPallets.forEach((p,wi)=>optimizeVehicles(p).forEach((v,vi)=>vehicles.push({...v,window:wi+1,vehicle:vi+1})));let perWeek=vehicles.length,before=db.config.beforePerWeek,avoidedWeek=Math.max(0,before-perWeek),weeks=db.config.periodWeeks,avoided=avoidedWeek*weeks,saving=avoided*db.config.cost,km=avoided*db.config.distance,ttw=km*db.config.ttw,wtw=km*(db.config.ttw+db.config.wtt),avg=vehicles.length?vehicles.reduce((a,v)=>a+v.occ,0)/vehicles.length:0;return{lines,pieces,pallets,windowPallets,vehicles,perWeek,avoidedWeek,avoided,saving,km,ttw,wtw,avg,red:before?avoidedWeek/before:0,crit:lines.filter(x=>x.status!=='OK')}}
function kpi(label,value,note){return `<div class="card"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div><div class="kpi-note">${note}</div></div>`}
function occStatus(o){return o>db.config.maxOcc/100?['ACIMA DE 100%','bad']:o<db.config.minOcc/100?['ABAIXO DE 85%','warn']:['OK','ok']}
function renderDashboard(){let t=totals();kpiGrid.innerHTML=[kpi('Peças',fmt(t.pieces),'Quantidade calculada'),kpi('Pallets',fmt(t.pallets),'Pela base de embalagens'),kpi('Carretas/semana',fmt(t.perWeek),'Plano otimizado'),kpi('Ocupação média',pct(t.avg),'Alvo 85%–100%'),kpi('Saving',money(t.saving),db.config.weekLabel),kpi('CO₂ TTW evitado',fmt(t.ttw/1000,2)+' t','Estimativa')].join('');windowCards.innerHTML=t.windowPallets.map((p,i)=>`<div class="pill">Janela ${i+1}: ${p} pallets</div>`).join('')||'<div class="smalltxt">Sem planejamento.</div>';planSummary.innerHTML=`O plano possui <b>${fmt(t.pallets)} pallets</b> e requer <b>${t.perWeek} carreta(s) por semana</b> em <b>${db.config.windows} janela(s)</b>. Economia potencial no período: <b>${money(t.saving)}</b>.`;criticalSummary.innerHTML=t.crit.length?`<span class="badge bad">${t.crit.length} material(is) crítico(s)</span><div class="smalltxt" style="margin-top:8px">Cadastre ou corrija embalagem/lote antes da contratação.</div>`:'<span class="badge ok">Todos os materiais com embalagem válida</span>';drawOccChart(t)}
function renderPlanning(){let t=totals();planMeta.textContent=`${db.plan.length} linhas • ${fmt(t.pieces)} peças • ${fmt(t.pallets)} pallets`;planRows.innerHTML=t.lines.map(x=>{let s=occStatus(x.status==='OK'?0.9:0);return `<tr><td>${esc(x.row.material)}</td><td>${esc(x.pk?.description||x.row.description||'')}</td><td class="num">${fmt(x.row.planned)}</td><td class="num">${fmt(x.row.firmed)}</td><td class="num">${fmt(x.qty)}</td><td class="num">${fmt(x.ipp)}</td><td class="num">${fmt(x.pallets)}</td><td><span class="badge ${x.status==='OK'?'ok':'bad'}">${x.status}</span></td></tr>`}).join('')}
function renderPackaging(){let q=(packSearch?.value||'').toLowerCase(),rows=db.packaging.filter(p=>!q||[p.material,p.description,p.supplier].some(v=>String(v||'').toLowerCase().includes(q)));packCount.textContent=db.packaging.length;packRows.innerHTML=rows.map(p=>{let i=db.packaging.indexOf(p);return `<tr><td>${esc(p.supplier)}</td><td><b>${esc(p.material)}</b></td><td>${esc(p.description)}</td><td class="num">${fmt(p.itemsPerBox)}</td><td class="num">${fmt(p.boxesPerPallet)}</td><td class="num"><b>${fmt(p.itemsPerPallet)}</b></td><td><button class="btn" onclick="openPackModal(${i})">Editar</button></td></tr>`}).join('')}
function renderConfig(){let fields=[['capacity','Capacidade da carreta (pallets)'],['minOcc','Ocupação mínima (%)'],['maxOcc','Ocupação máxima (%)'],['cost','Custo por viagem (R$)'],['distance','Distância da rota (km)'],['ttw','Fator TTW kg CO₂e/km'],['wtt','Fator WTT kg CO₂e/km'],['windows','Janelas por semana'],['periodWeeks','Semanas no período'],['beforePerWeek','Veículos antes/semana'],['weekLabel','Identificação do período']];configFields.innerHTML=fields.map(([k,l])=>`<div class="field"><label>${l}</label><input id="cfg_${k}" ${k==='weekLabel'?'type="text"':'type="number" step="0.00001"'} value="${esc(db.config[k])}"></div>`).join('')}
function saveConfig(){Object.keys(db.config).forEach(k=>{let e=document.getElementById('cfg_'+k);if(e)db.config[k]=k==='weekLabel'?e.value:+e.value});persist();render()}
function renderImpacts(){let t=totals();impactKpis.innerHTML=[kpi('Viagens evitadas',fmt(t.avoided),`${fmt(t.avoidedWeek)} por semana`),kpi('Redução',pct(t.red),'vs cenário anterior'),kpi('Saving',money(t.saving),db.config.weekLabel),kpi('Km evitados',fmt(t.km)+' km','No período'),kpi('CO₂ TTW',fmt(t.ttw/1000,2)+' t','Evitado'),kpi('CO₂ WTW',fmt(t.wtw/1000,2)+' t','Evitado')].join('');impactText.innerHTML=`A redução de <b>${db.config.beforePerWeek}</b> para <b>${t.perWeek}</b> veículo(s) semanais evita <b>${t.avoided}</b> viagens no período, aproximadamente <b>${fmt(t.km)} km</b> e <b>${fmt(t.ttw/1000,2)} t CO₂e TTW</b>.`;historyRows.innerHTML=(db.history||[]).map(h=>`<tr><td>${h.date}</td><td>${h.period}</td><td>${h.pallets}</td><td>${h.vehicles}</td><td>${h.occ}</td><td>${h.saving}</td><td>${h.co2}</td></tr>`).join('');drawImpactChart(t)}
function saveScenario(){let t=totals();db.history.unshift({date:new Date().toLocaleString('pt-BR'),period:db.config.weekLabel,pallets:t.pallets,vehicles:t.perWeek,occ:pct(t.avg),saving:money(t.saving),co2:fmt(t.ttw/1000,2)+' t'});persist();render()}
function drawOccChart(t){barChart('occChart',t.vehicles.map(v=>`J${v.window}-C${v.vehicle}`),t.vehicles.map(v=>v.occ*100),100,true)}function drawImpactChart(t){barChart('impactChart',['Antes','Depois'],[db.config.beforePerWeek,t.perWeek],Math.max(db.config.beforePerWeek,t.perWeek,1)*1.25,false)}function barChart(id,labels,vals,max,percent){let s=document.getElementById(id);if(!s)return;s.innerHTML='';let W=700,H=260,mx=max||Math.max(1,...vals)*1.2,w=560/Math.max(1,vals.length);vals.forEach((v,i)=>{let h=165*v/mx,x=70+i*w,y=210-h,c=percent?(v<db.config.minOcc?'#e6b800':v>db.config.maxOcc?'#c0504d':'#70ad47'):(i?'#7da6c7':'#1f4e79');let r=document.createElementNS('http://www.w3.org/2000/svg','rect');Object.entries({x,y,width:Math.max(22,w-16),height:h,rx:7,fill:c}).forEach(([k,a])=>r.setAttribute(k,a));s.appendChild(r);svgText(s,x+(w-16)/2,y-8,percent?fmt(v,1)+'%':fmt(v),12);svgText(s,x+(w-16)/2,234,labels[i],10)})}function svgText(s,x,y,v,size){let e=document.createElementNS('http://www.w3.org/2000/svg','text');e.setAttribute('x',x);e.setAttribute('y',y);e.setAttribute('font-size',size);e.setAttribute('text-anchor','middle');e.setAttribute('fill','#4b5563');e.textContent=v;s.appendChild(e)}
function renderLoadSelectors(){let t=totals(),wins=[...new Set(t.vehicles.map(v=>v.window))];loadWindow.innerHTML=wins.map(w=>`<option value="${w}">Janela ${w}</option>`).join('');refreshLoadVehicles(false)}function refreshLoadVehicles(draw=true){let t=totals(),w=+loadWindow.value||1,vs=t.vehicles.filter(v=>v.window===w);let prev=+loadVehicle.value||1;loadVehicle.innerHTML=vs.map(v=>`<option value="${v.vehicle}">Carreta ${v.vehicle}</option>`).join('');if(vs.some(v=>v.vehicle===prev))loadVehicle.value=prev;if(draw)render3DLoad()}
function render3DLoad(){let t=totals(),w=+loadWindow.value||1,vn=+loadVehicle.value||1,v=t.vehicles.find(x=>x.window===w&&x.vehicle===vn)||{pallets:0,occ:0,window:w,vehicle:vn},st=occStatus(v.occ);loadKpis.innerHTML=[kpi('Janela',v.window,'Selecionada'),kpi('Carreta',v.vehicle,'Selecionada'),kpi('Pallets',v.pallets+' / '+db.config.capacity,'Carregamento previsto'),kpi('Ocupação',pct(v.occ),'Taxa calculada'),kpi('Status',st[0],'Meta 85%–100%'),kpi('Posições livres',Math.max(0,db.config.capacity-v.pallets),'Capacidade residual')].join('');loadDetail.innerHTML=`<b>Janela ${v.window} • Carreta ${v.vehicle}</b><br>${v.pallets} pallets previstos, ocupação de ${pct(v.occ)}. <span class="badge ${st[1]}">${st[0]}</span>`;drawTruck(v.pallets);drawLayers(v.pallets)}
function drawLayers(count){let html='';for(let layer=0;layer<2;layer++){html+=`<b>Camada ${layer+1}</b><div class="layer-map">`;for(let i=0;i<26;i++){let pos=layer*26+i;html+=`<i class="layer-cell ${pos<count?'':'empty'}"></i>`}html+='</div>'}layerMaps.innerHTML=html}
function drawTruck(count){let c=loadCanvas,ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(W/2,H/2+40);ctx.rotate(angle*Math.PI/180);let sx=24,sy=36,g=5,cols=13,rows=2;for(let layer=0;layer<2;layer++){let ox=-cols*(sx+g)/2,oy=-rows*(sy+g)/2-layer*95;for(let r=0;r<rows;r++)for(let col=0;col<cols;col++){let idx=layer*26+r*cols+col,x=ox+col*(sx+g),y=oy+r*(sy+g);ctx.fillStyle=idx<count?'#c58e55':'#f7f8fa';ctx.strokeStyle=idx<count?'#805629':'#94a3b8';ctx.setLineDash(idx<count?[]:[4,3]);ctx.fillRect(x,y,sx,sy);ctx.strokeRect(x,y,sx,sy)}ctx.setLineDash([]);ctx.strokeStyle='#64748b';ctx.lineWidth=3;ctx.strokeRect(ox-12,oy-12,cols*(sx+g)+18,rows*(sy+g)+18)}ctx.restore()}
function rotateLoad(d){angle+=d;render3DLoad()}function resetLoadView(){angle=-36;render3DLoad()}loadCanvas?.addEventListener('mousedown',e=>{drag=true;lastX=e.clientX});window.addEventListener('mouseup',()=>drag=false);window.addEventListener('mousemove',e=>{if(!drag)return;angle+=(e.clientX-lastX)*.25;lastX=e.clientX;render3DLoad()});
function openPackModal(i=-1){editingPack=i;let p=i>=0?db.packaging[i]:{supplier:'',supplierCode:'',material:'',description:'',itemsPerBox:0,boxesPerPallet:0,itemsPerPallet:0,unit:'PC'};packModalTitle.textContent=i>=0?'Editar material':'Novo material';let fs=[['supplier','Fornecedor'],['supplierCode','Código fornecedor'],['material','Material'],['description','Descrição'],['itemsPerBox','Itens por caixa'],['boxesPerPallet','Caixas por pallet'],['itemsPerPallet','Itens por pallet (lote)'],['unit','Unidade']];packForm.innerHTML=fs.map(([k,l])=>`<div class="field"><label>${l}</label><input id="pf_${k}" ${k.startsWith('items')||k.startsWith('boxes')?'type="number"':''} value="${esc(p[k])}"></div>`).join('');packModal.classList.add('show')}function closePackModal(){packModal.classList.remove('show')}function savePackRecord(){let obj={};['supplier','supplierCode','material','description','itemsPerBox','boxesPerPallet','itemsPerPallet','unit'].forEach(k=>{let v=document.getElementById('pf_'+k).value;obj[k]=['itemsPerBox','boxesPerPallet','itemsPerPallet'].includes(k)?+v:v});if(!obj.itemsPerPallet)obj.itemsPerPallet=obj.itemsPerBox*obj.boxesPerPallet;if(editingPack>=0)db.packaging[editingPack]=obj;else db.packaging.unshift(obj);persist();closePackModal();render()}
function importPackaging(e){readWorkbook(e.target.files[0],rows=>{let cols=Object.keys(rows[0]||{}),m=autoMap(cols);db.packaging=rows.map(r=>({supplier:r[m.supplier]||'',supplierCode:'',material:r[m.material]||'',description:r[m.description]||'',itemsPerBox:num(r[m.itemsPerBox]),boxesPerPallet:num(r[m.boxesPerPallet]),itemsPerPallet:num(r[m.itemsPerPallet])||num(r[m.itemsPerBox])*num(r[m.boxesPerPallet]),unit:'PC'})).filter(x=>x.material);persist();render()})}
function readPlanningFile(e){let f=e.target.files[0];if(!f)return;let reader=new FileReader();reader.onload=x=>{currentBook=XLSX.read(x.target.result,{type:'array',cellDates:true});sheetSelect.innerHTML=currentBook.SheetNames.map(n=>`<option>${n}</option>`).join('');changePlanSheet();mapModal.classList.add('show')};reader.readAsArrayBuffer(f)}
function parseDateHeader(v){
  if(v instanceof Date&&!isNaN(v))return new Date(v.getFullYear(),v.getMonth(),v.getDate());
  let s=String(v||'').trim(),m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);
  if(m)return new Date(+m[3],+m[2]-1,+m[1]);
  let d=new Date(s);return isNaN(d)?null:new Date(d.getFullYear(),d.getMonth(),d.getDate());
}
function isoDate(d){if(!d)return'';return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function isoWeek(d){let x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));let y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function dateRangeLabel(a,b){if(!a||!b)return'';let da=new Date(a+'T00:00:00'),dbb=new Date(b+'T00:00:00'),wa=isoWeek(da),wb=isoWeek(dbb);return wa===wb?`S${wa}`:`S${wa}–S${wb}`}
function rangeSum(row,dateCols,start,end){if(!start||!end)return 0;let a=new Date(start+'T00:00:00'),b=new Date(end+'T23:59:59');return dateCols.reduce((sum,o)=>sum+(o.date>=a&&o.date<=b?num(row[o.col]):0),0)}
function changePlanSheet(){
  let ws=currentBook.Sheets[sheetSelect.value],rows=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false,dateNF:'dd.mm.yyyy'});currentRows=rows;
  let cols=Object.keys(rows[0]||{}),auto=autoMap(cols),dateCols=cols.map(c=>({col:c,date:parseDateHeader(c)})).filter(x=>x.date).sort((a,b)=>a.date-b.date);
  let textCol=cols.find(c=>['texto','text','mrp element','elemento mrp'].includes(String(c).toLowerCase().trim()))||cols.find(c=>String(c).toLowerCase().includes('texto'));
  let sapMode=!!(textCol&&dateCols.length);window.__planningImport={sapMode,dateCols,textCol};
  if(sapMode){
    let first=isoDate(dateCols[0].date),last=isoDate(dateCols[dateCols.length-1].date);
    mappingFields.innerHTML=`
      <div class="field"><label>Material</label><select id="map_material">${cols.map(c=>`<option ${c===auto.material?'selected':''}>${esc(c)}</option>`).join('')}</select></div>
      <div class="field"><label>Descrição</label><select id="map_description"><option value="">— não usar —</option>${cols.map(c=>`<option ${c===auto.description?'selected':''}>${esc(c)}</option>`).join('')}</select></div>
      <div class="field"><label>Coluna do tipo de recebimento</label><select id="map_receiptType">${cols.map(c=>`<option ${c===textCol?'selected':''}>${esc(c)}</option>`).join('')}</select></div>
      <div class="field"><label>Formato detectado</label><input value="Receipts por data (SAP)" disabled></div>
      <div class="period-box"><b>Planned Receipts</b><div class="period-grid">
        <div class="field"><label>Data inicial</label><input id="plannedStart" type="date" value="${first}" onchange="updatePeriodInfo()"></div>
        <div class="field"><label>Data final</label><input id="plannedEnd" type="date" value="${last}" onchange="updatePeriodInfo()"></div>
      </div><div class="smalltxt" id="plannedPeriodInfo"></div></div>
      <div class="period-box"><b>Firmed Receipts</b><div class="period-grid">
        <div class="field"><label>Data inicial</label><input id="firmedStart" type="date" value="${first}" onchange="updatePeriodInfo()"></div>
        <div class="field"><label>Data final</label><input id="firmedEnd" type="date" value="${last}" onchange="updatePeriodInfo()"></div>
      </div><div class="smalltxt" id="firmedPeriodInfo"></div></div>`;
    setTimeout(updatePeriodInfo,0);
  }else{
    mappingFields.innerHTML=[['material','Material'],['description','Descrição'],['planned','Planned Receipts'],['firmed','Firmed Receipts']].map(([k,l])=>`<div class="field"><label>${l}</label><select id="map_${k}"><option value="">— não usar —</option>${cols.map(c=>`<option ${c===auto[k]?'selected':''}>${esc(c)}</option>`).join('')}</select></div>`).join('');
  }
  previewTable.innerHTML='<tr>'+cols.slice(0,10).map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>'+rows.slice(0,7).map(r=>'<tr>'+cols.slice(0,10).map(c=>`<td>${esc(r[c])}</td>`).join('')+'</tr>').join('');
}
function updatePeriodInfo(){
  let ps=document.getElementById('plannedStart')?.value,pe=document.getElementById('plannedEnd')?.value,fs=document.getElementById('firmedStart')?.value,fe=document.getElementById('firmedEnd')?.value;
  let pi=document.getElementById('plannedPeriodInfo'),fi=document.getElementById('firmedPeriodInfo');
  if(pi)pi.textContent=ps&&pe?`Período selecionado: ${new Date(ps+'T00:00:00').toLocaleDateString('pt-BR')} a ${new Date(pe+'T00:00:00').toLocaleDateString('pt-BR')} • ${dateRangeLabel(ps,pe)}`:'Selecione o período.';
  if(fi)fi.textContent=fs&&fe?`Período selecionado: ${new Date(fs+'T00:00:00').toLocaleDateString('pt-BR')} a ${new Date(fe+'T00:00:00').toLocaleDateString('pt-BR')} • ${dateRangeLabel(fs,fe)}`:'Selecione o período.';
}
function applyMapping(){
  let imp=window.__planningImport||{};
  if(imp.sapMode){
    let material=document.getElementById('map_material').value,description=document.getElementById('map_description').value,typeCol=document.getElementById('map_receiptType').value;
    let ps=document.getElementById('plannedStart').value,pe=document.getElementById('plannedEnd').value,fs=document.getElementById('firmedStart').value,fe=document.getElementById('firmedEnd').value;
    if(!material||!typeCol){alert('Mapeie Material e Tipo de recebimento.');return}
    if((ps&&!pe)||(!ps&&pe)||(fs&&!fe)||(!fs&&fe)){alert('Informe data inicial e final para cada período utilizado.');return}
    if(ps&&pe&&ps>pe){alert('No Planned Receipts, a data inicial deve ser anterior à final.');return}
    if(fs&&fe&&fs>fe){alert('No Firmed Receipts, a data inicial deve ser anterior à final.');return}
    let agg=new Map();
    currentRows.forEach(r=>{
      let mat=String(r[material]||'').trim();if(!mat)return;
      let typ=String(r[typeCol]||'').trim().toLowerCase(),isP=typ.includes('planned receipt'),isF=typ.includes('firmed receipt');if(!isP&&!isF)return;
      let key=mat.toUpperCase(),cur=agg.get(key)||{material:mat,description:description?String(r[description]||''):'',planned:0,firmed:0};
      if(isP&&ps&&pe)cur.planned+=rangeSum(r,imp.dateCols,ps,pe);
      if(isF&&fs&&fe)cur.firmed+=rangeSum(r,imp.dateCols,fs,fe);
      if(!cur.description&&description)cur.description=String(r[description]||'');
      agg.set(key,cur);
    });
    db.plan=[...agg.values()].filter(x=>x.planned||x.firmed);
    db.selectedPeriods={planned:{start:ps,end:pe,label:dateRangeLabel(ps,pe)},firmed:{start:fs,end:fe,label:dateRangeLabel(fs,fe)}};
    let labels=[db.selectedPeriods.planned.label,db.selectedPeriods.firmed.label].filter(Boolean);if(labels.length)db.config.weekLabel=[...new Set(labels)].join(' / ');
    persist();closeMapModal();render();return;
  }
  let mm={};['material','description','planned','firmed'].forEach(k=>{let el=document.getElementById('map_'+k);mm[k]=el?el.value:''});
  if(!mm.material){alert('Mapeie a coluna Material.');return}
  db.plan=currentRows.map(r=>({material:r[mm.material]||'',description:mm.description?r[mm.description]||'':'',planned:mm.planned?num(r[mm.planned]):0,firmed:mm.firmed?num(r[mm.firmed]):0})).filter(x=>x.material);
  persist();closeMapModal();render();
}
function closeMapModal(){mapModal.classList.remove('show')}function reprocessPlan(){render()}function loadDemoPlan(){db.plan=clone(window.DEMO_PLAN||[]);persist();render()}
function autoMap(cols){let defs={material:['material','item','part','codigo','número','numero'],description:['desc','descrição','descricao'],planned:['planned receipts','planned'],firmed:['firmed receipts','firmed'],supplier:['fornecedor','supplier'],itemsPerBox:['itens por caixa','items/box','parts/hu','pecas caixa','peças caixa'],boxesPerPallet:['caixas por pallet','box pallet','hu/pallet'],itemsPerPallet:['itens por pallet','total itens pallet','lote','parts/pallet']},o={};Object.keys(defs).forEach(k=>o[k]=cols.find(c=>defs[k].some(t=>String(c).toLowerCase().includes(t)))||cols[0]);return o}function num(v){if(typeof v==='number')return v;return +String(v||0).replace(/\s/g,'').replace(/\./g,'').replace(',','.')||0}function readWorkbook(file,cb){let r=new FileReader();r.onload=e=>{let wb=XLSX.read(e.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];cb(XLSX.utils.sheet_to_json(ws,{defval:''}))};r.readAsArrayBuffer(file)}
function exportBackup(){let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='wk_transport_backup.json';a.click()}function exportProcessed(){let t=totals(),rows=t.lines.map(x=>({Material:x.row.material,Descricao:x.pk?.description||x.row.description,Planned:x.row.planned,Firmed:x.row.firmed,Quantidade:x.qty,ItensPallet:x.ipp,Pallets:x.pallets,Status:x.status})),ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Resultado');XLSX.writeFile(wb,'WK_resultado_planejamento.xlsx')}function resetAll(){if(confirm('Restaurar dados iniciais?')){db=clone(DEFAULT);persist();render()}}
function render(){renderDashboard();renderPlanning();renderPackaging();renderConfig();renderImpacts();renderLoadSelectors()}render();
